language: python
python: 3.7
sudo: true
dist: xenial
env:
  - GH_USER_NAME: '"Miro Hrončok"'
    GH_USER_EMAIL: miro@hroncok.cz
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install aiohttp
  - git clone https://pagure.io/forks/churchyard/fedora-misc-package-utilities.git --single-branch -b find-orphaned-packages --depth 1
script:
  - python fedora-misc-package-utilities/find-orphaned-packages | sort | tee README
after_success:
  - '[ $TRAVIS_EVENT_TYPE != cron ] && exit 0'
  - openssl aes-256-cbc -K $encrypted_71f98c6bc319_key -iv $encrypted_71f98c6bc319_iv -in github_deploy_key.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - git remote add ssh git@github.com:hroncok/fedora-orphaned-packages.git
  - git diff
  - git commit -am"Autocommit"
  - git pull --rebase -X ours
  - git push ssh HEAD:master
